### ISSUE TITLE
Upgrade Bouncy Castle libraries to 1.53

### ISSUE THREAD

**Issue by jochenberger** [phax/as2-lib#10]
There are some issues with 1.52 and Java 8. I can do the upgrade myself if you're okay with that.

**Comment by phax** [comment]
Done. I will create a 2.2.2 release out of it

**Comment by phax** [comment]
I did this myself, because I have a lot of other libraries using BC and I needed to update and release all of them. So it was part of a bigger process :) But thanks for the offer!
