### ISSUE TITLE
does as2-lib v4.0.2 support the AES 256 in encryption algorithm?

### ISSUE THREAD

**Issue by Gentle-Chen** [phax/as2-lib#101]
Hi Philip,
Does as2-lib v4.0.2 support the AES 256 in encryption algorithm?
If not, which version support?

Thanks.

**Comment by Gentle-Chen** [comment]
Hi Philip,

As I checked the source code, found that v4.0.2 cannot support the AES256, but v4.1.0 can do it.

So if i upgrade v4.0.2 to v4.1.0, is it anything I need to pay attention to?
v4.0.2
![from v4 0 2 ](https://user-images.githubusercontent.com/26357197/71713607-5e6c5300-2e45-11ea-9ab6-6e124d041600.png)
v4.1.0
![from v4 1 0 ](https://user-images.githubusercontent.com/26357197/71713609-60cead00-2e45-11ea-9db7-78c6fed1fa2f.png)

**Comment by phax** [comment]
Hi. I don't know exactly.
Please check the News and Noteworthy page in the Wiki.
Additionally the latest version is 4.5.0 which fixes other issues as well....
Am on vacation atm. Can check next week....

**Comment by phax** [comment]
@Gentle-Chen so you upgraded to 4.5.0 than? Did it work as expected?
