### ISSUE TITLE
AbstractStorageModule::getFile  - method is final

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#105]
Hi Philip,
The getFile method in AbstractStorageModule class is final now.In older versions I think until 4.5.0 It wasn't final and we could override this method.
We would like to override this method to add our functionality.
Could you please remove the final keyword from this method.

Thanks,
Itay

**Comment by phax** [comment]
Hi. Sorry for the inconvenience. Part of 4.5.5 release. I made myself a note to avoid doing this again ;-)

**Comment by ihudedi** [comment]
When 4.5.5 will be released?

**Comment by ihudedi** [comment]
We need this version soon.I can't use snapshot version.
Thanks,
Itay

**Comment by phax** [comment]
I don't know. Are any of the changes after 4.5.0 criticial for you?

**Comment by ihudedi** [comment]
Yes I need the fix for the bcMail.

**Comment by phax** [comment]
Ok building right now. In approx. half an hours it is on Maven Central

**Comment by ihudedi** [comment]
10x a lot:)
