### ISSUE TITLE
Content-Length header not being sent?

### ISSUE THREAD

**Issue by uplink42** [phax/as2-lib#109]
Hello and first of all thanks for this great library.

I'm currently performing some tests with a trading partner and apparently the messages are not being processed in the other end because the 'Content-Length' header is missing. I assume this has to do with the way the trasnfer encoding works with as2-lib (it's being set as chunked). Is there any way to disable this behavior and force it to send the 'content-length' header? I couldn't find anything in the documentation.

**Comment by phax** [comment]
This is a tricky one, because it depends on many parameters:
* The source you are using (stream based or fully available)
* The usage of compression or not
* The usage of encryption or not
* The Content-Transfer-Encoding used
* Whether chunked encoding is used or not

I've scanned the code and I've seen no evidence of setting the header anywhere. It is only evaluated when reading incoming messages...

**Comment by phax** [comment]
Ah okay, so than it is something Apache HttpClient does on it's own :)
Than it happens in `AS2HttpClient.send` - lines 172ff

**Comment by uplink42** [comment]
I see. Thanks

Would an option to disable stream based requests be a possibility? There's still a few AS2 clients out there that don't support chunked encoding.

**Comment by phax** [comment]
Okay, let me see what I can do...

**Comment by uplink42** [comment]
Thank you for your time :)

**Comment by uplink42** [comment]
@phax  did you manage to find anything? I have been hitting my head against the wall trying to create a message witouth chunked encoding but so far I'm unable to. 

I noticed the option to send chunked messages replaced the old 'default' method in version 4.4

`Remove support for the old HttpUrlConnection, therefore making "large file support" the default (see #87)`

Is there a chance we can have an option to toggle this back? Some AS2 clients are unable to recieve chunked messages and simply die. :(

**Comment by phax** [comment]
I tried to add the Content-Length; can you please try with 4.6.1-SNAPSHOT? Thx

**Comment by phax** [comment]
Closing this, as it is contained in 4.6.1
