### ISSUE TITLE
It should be easier to override the catch-all behavior in AS2SenderModule

### ISSUE THREAD

**Issue by jochenberger** [phax/as2-lib#11]
If an exception occurs while receiving an MDN, the error is just logged but not thrown out of the module. The calling code has no way to know that there was an error.
I suggest extracting the relevant code (AS2SenderModule, lines 659-664) into a protected method. or calling an overridable no-op method from the `catch block`.

**Comment by phax** [comment]
```java
@OverrideOnDemand
  protected void onReceivedMDNError (@Nonnull final AS2Message aMsg, @Nonnull final OpenAS2Exception ex)
```
