### ISSUE TITLE
Possibility to initialize CertificateFactory with keystore as InputStream or byte[]

### ISSUE THREAD

**Issue by yaskovdev** [phax/as2-lib#110]
I am using your library with Spring Boot application. Everything works fine, but there is a small issue with the `CertificateFactory` initialization. Current implementation of `CertificateFactory` can only be initialized using the filename of my keystore (via passing the filename as the `ATTR_FILENAME` value to the `CertificateFactory#initDynamicComponent` method).

This causes issues when the keystore file resides not in the filesystem of the OS where I run my AS2 server, but is located inside the Spring Boot JAR file. This is because Spring cannot resolve the proper filename for a file located inside the JAR, it will try to find the file in the filesystem and fail (details [here](https://smarterco.de/java-load-file-from-classpath-in-spring-boot/)).

Please add possibility to initialize `CertificateFactory` not with the filename of the keystore, but with the `InputStream` (or `byte[]`) of the keystore. I can see that `AS2Client` already provides such possibility (see `AS2ClientSettings#setKeyStore(IKeyStoreType, byte[], String)` method). Unfortunately I was not able to find such possibility for AS2 server.

Thank you.

**Comment by phax** [comment]
Sorry for the delay, but I think here's a solution for you (should work with 4.6.3):
1. Create a custom base class of `CertificateFactory`
2. On init, ensure that no filename is present
3. After loading you have an empty keystore - now call `load (new ByteArrayInputStream (bytes), "password".toCharArray ())` 

See e.g. the demo class in the previouse commit - untested but should work

**Comment by yaskovdev** [comment]
@phax, I have tried the approach you suggested, it works very well. Thank you for the great library.

Not sure what to do with the issue. It most likely can be just closed, cannot it?

**Comment by phax** [comment]
Thanks for verifying it :) Happy messaging
