### ISSUE TITLE
AS2 version 1.2

### ISSUE THREAD

**Issue by AlexandruCiobanu** [phax/as2-lib#111]
Hi,
Is there any way to specify as2 version 1.2?

Thanks,
Alex

**Comment by phax** [comment]
AS2 1.2 means: indicate the support of the EDIINT-Features header field as defined by RFC 6017

Currently there is no way to specify a different version.

Putting this is a member into `IAS2Session` would make sense. right?

**Comment by AlexandruCiobanu** [comment]
I believe it would.

**Comment by phax** [comment]
Than lets do it :)

**Comment by phax** [comment]
Part of 4.6.1
