### ISSUE TITLE
AS2 server using servlet

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#113]
Hi,
I'm trying to replace AS2 Server with servlet and I have few questions.
 Till now, when we needed to change properties we restarted the AS2 server and not the application.
 How can I refresh properties in servlet while running? Also in AS2 server we take care of MDN messages, and I don't see that servlet support it
 
 Regards
Itay

**Comment by phax** [comment]
Hi,
you mean the "config.xml" file you pass in as the commandline parameter to "main"?
Well you can setup all the components in code - but there is no built-in reload mechanism.
What are the things you want to change??

Concerning async MDN receival - yes, you are correct. Can you eventuall create a PR?
Thanks, Philip

**Comment by ihudedi** [comment]
Hi Philip,
Thanks for the commit for reloading config.
Regarding the MDN servlet.Do you plan to develop this as well?
Thanks,
Itay

**Comment by phax** [comment]
Hi Itay,
no, currently I don't have plans. Additionally I am now on vacation for until August 10th :)
Any PR is welcome.

**Comment by phax** [comment]
So, the MDN servlet is finally available in 4.6.4
