### ISSUE TITLE
AS2 server - AS2 Keystore is loaded only when server is up.any change to the keystore isn't taking into consideration

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#117]
Hi Philip,
Currently the AS2 Keystore is saved in memory after server is started.
When I modified the keystore and try to connect to the AS2 server that entry doesn't exist because the AS2 server doens't load the keystore every time we are trying to access the kestore.
Is it possible  to load the keystore when access him?
Thanks,
Itay

**Comment by avnerw74** [comment]
Hi Philip,
Happy new year!
I wonder if you have an answer/recommendation to the above question.
Thanks,
Avner

**Comment by phax** [comment]
Hi guys,
Happy New Year to you too.
I just looked at it, and loading on every access does not really makes sense to me.
What I could offer is to implement a "reload" method in class `com.helger.as2lib.cert.CertificateFactory` that you can trigger when you feel it is time.
Would that work for you?

**Comment by ihudedi** [comment]
Hi @phax 
Yes reload method will be great.
Thanks,
Itay.

**Comment by avnerw74** [comment]
Hi @phax ,
Yes, that would work for our customers so they can just refresh using an API we'll expose, instead of bouncing our server
Thanks!
Avner

**Comment by phax** [comment]
Part of 4.6.4 release

**Comment by avnerw74** [comment]
Thanks Philip!

**Comment by ihudedi** [comment]
Hi @phax 
What time 4.6.4 will be release?
Thanks,
Itay

**Comment by phax** [comment]
Waiting for a quick test if the new async MDN servlet works - if yes, pretty soon. I assume end of the week/start of next week

**Comment by ihudedi** [comment]
Hi @phax 
Do you have async mdn servlet?
what about servlet for messages? it it new?
Thanks,
Itay

**Comment by phax** [comment]
No, that was "always" there. It's part of the "as2-servlet" submodule and roughly described at https://github.com/phax/as2-lib/wiki/Submodule-as2%E2%80%90servlet
