### ISSUE TITLE
Question - AS2-lib client with AS2 server that works in https

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#119]
Hi @phax 
Can I send AS2 messages via the as2-lib to https server?
Should I configure some properties or only set the correct url?
Thanks,
Itay

**Comment by phax** [comment]
Hi, just send to them. If the server is configured correctly, you don't need to set anything. More details follow later

**Comment by phax** [comment]
You can customize `AbstractHttpSenderModule.createSSLContext()` to customize what's allowed and what isn't

**Comment by phax** [comment]
Hi Itay,
closing this one, as I guess it just worked.
