### ISSUE TITLE
MainSendToMendelsonTestServer test is not working when using VPN

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#120]
Hi Philip,
I tried to send as2 messages to mendleson test server using the class MainSendToMendelsonTestServer
but with no success.
Getting : connection reset
2021-02-09 13:29:17,398 ERROR [main] (AS2Client:444) -  Error sending AS2 message
com.helger.as2lib.processor.AS2ProcessorException: Processor 'DefaultMessageProcessor' threw exception:
com.helger.as2lib.processor.AS2ProcessorException: Processor 'DefaultMessageProcessor' threw exception:
com.helger.as2lib.exception.WrappedAS2Exception: java.net.SocketException: Connection reset
1.: com.helger.as2lib.exception.WrappedAS2Exception.wrap(WrappedAS2Exception.java:66)
2.: com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:940)
3.: com.helger.as2lib.processor.AbstractMessageProcessor.executeAction(AbstractMessageProcessor.java:203)
4.: com.helger.as2lib.processor.DefaultMessageProcessor.handle(DefaultMessageProcessor.java:65)
5.: com.helger.as2lib.processor.resender.ImmediateResenderModule.handle(ImmediateResenderModule.java:95)
6.: com.helger.as2lib.processor.AbstractMessageProcessor.executeAction(AbstractMessageProcessor.java:203)
7.: com.helger.as2lib.processor.DefaultMessageProcessor.handle(DefaultMessageProcessor.java:65)
8.: com.helger.as2lib.processor.sender.AbstractSenderModule.doResend(AbstractSenderModule.java:148)
9.: com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:942)
10.: com.helger.as2lib.client.AS2Client.sendSynchronous(AS2Client.java:435)
11.: com.helger.as2lib.test.MainSendToMendelsonServerTest.main(MainSendToMendelsonServerTest.java:152)
==> [1] caused by java.net.SocketException: Connection reset
1.: java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
2.: java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
3.: org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
4.: org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
5.: org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
6.: org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
7.: org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
8.: org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
9.: org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
10.: org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
11.: org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
12.: org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
13.: org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
14.: org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
15.: org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
16.: org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
17.: org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
18.: org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
19.: org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
20.: com.helger.as2lib.util.http.AS2HttpClient.send(AS2HttpClient.java:209)
21.: com.helger.as2lib.processor.sender.AS2SenderModule._sendViaHTTP(AS2SenderModule.java:828)
22.: com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:925)
  [9 elements omitted -- com.helger.as2lib.processor.AbstractMessageProcessor.executeAction(AbstractMessageProcessor.java:203)]
1.: com.helger.as2lib.processor.AbstractMessageProcessor.executeAction(AbstractMessageProcessor.java:217)
2.: com.helger.as2lib.processor.DefaultMessageProcessor.handle(DefaultMessageProcessor.java:65)
3.: com.helger.as2lib.processor.resender.ImmediateResenderModule.handle(ImmediateResenderModule.java:95)
4.: com.helger.as2lib.processor.AbstractMessageProcessor.executeAction(AbstractMessageProcessor.java:203)
5.: com.helger.as2lib.processor.DefaultMessageProcessor.handle(DefaultMessageProcessor.java:65)
6.: com.helger.as2lib.processor.sender.AbstractSenderModule.doResend(AbstractSenderModule.java:148)
7.: com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:942)
8.: com.helger.as2lib.client.AS2Client.sendSynchronous(AS2Client.java:435)
9.: com.helger.as2lib.test.MainSendToMendelsonServerTest.main(MainSendToMendelsonServerTest.java:152)
	at com.helger.as2lib.processor.AbstractMessageProcessor.executeAction(AbstractMessageProcessor.java:217) ~[as2-lib-4.6.3.jar:4.6.3]
	at com.helger.as2lib.processor.DefaultMessageProcessor.handle(DefaultMessageProcessor.java:65) ~[as2-lib-4.6.3.jar:4.6.3]
	at com.helger.as2lib.processor.sender.AbstractSenderModule.doResend(AbstractSenderModule.java:148) ~[as2-lib-4.6.3.jar:4.6.3]
	at com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:942) ~[as2-lib-4.6.3.jar:4.6.3]
	at com.helger.as2lib.client.AS2Client.sendSynchronous(AS2Client.java:435) [as2-lib-4.6.3.jar:4.6.3]
	at com.helger.as2lib.test.MainSendToMendelsonServerTest.main(MainSendToMendelsonServerTest.java:152) [test-classes/:?]
2021-02-09 13:29:17,398 ERROR [main] (MainSendToMendelsonServerTest:155) -  --------------------------------------------------------------------------
2021-02-09 13:29:17,398 ERROR [main] (MainSendToMendelsonServerTest:156) -  Exception in MainSendToMendelsonServerTest error: 
com.helger.as2lib.processor.AS2ProcessorException: Processor 'DefaultMessageProcessor' threw exception:
com.helger.as2lib.processor.AS2ProcessorException: Processor 'DefaultMessageProcessor' threw exception:
com.helger.as2lib.exception.WrappedAS2Exception: java.net.SocketException: Connection reset
1.: com.helger.as2lib.exception.WrappedAS2Exception.wrap(WrappedAS2Exception.java:66)
2.: com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:940)
3.: com.helger.as2lib.processor.AbstractMessageProcessor.executeAction(AbstractMessageProcessor.java:203)
4.: com.helger.as2lib.processor.DefaultMessageProcessor.handle(DefaultMessageProcessor.java:65)
5.: com.helger.as2lib.processor.resender.ImmediateResenderModule.handle(ImmediateResenderModule.java:95)
6.: com.helger.as2lib.processor.AbstractMessageProcessor.executeAction(AbstractMessageProcessor.java:203)
7.: com.helger.as2lib.processor.DefaultMessageProcessor.handle(DefaultMessageProcessor.java:65)
8.: com.helger.as2lib.processor.sender.AbstractSenderModule.doResend(AbstractSenderModule.java:148)
9.: com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:942)
10.: com.helger.as2lib.client.AS2Client.sendSynchronous(AS2Client.java:435)
11.: com.helger.as2lib.test.MainSendToMendelsonServerTest.main(MainSendToMendelsonServerTest.java:152)
==> [1] caused by java.net.SocketException: Connection reset
1.: java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
2.: java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
3.: org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
4.: org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
5.: org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
6.: org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
7.: org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
8.: org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
9.: org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
10.: org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
11.: org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
12.: org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
13.: org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
14.: org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
15.: org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
16.: org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
17.: org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
18.: org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
19.: org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
20.: com.helger.as2lib.util.http.AS2HttpClient.send(AS2HttpClient.java:209)
21.: com.helger.as2lib.processor.sender.AS2SenderModule._sendViaHTTP(AS2SenderModule.java:828)
22.: com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:925)
  [9 elements omitted -- com.helger.as2lib.processor.AbstractMessageProcessor.executeAction(AbstractMessageProcessor.java:203)]
1.: com.helger.as2lib.processor.AbstractMessageProcessor.executeAction(AbstractMessageProcessor.java:217)
2.: com.helger.as2lib.processor.DefaultMessageProcessor.handle(DefaultMessageProcessor.java:65)
3.: com.helger.as2lib.processor.resender.ImmediateResenderModule.handle(ImmediateResenderModule.java:95)
4.: com.helger.as2lib.processor.AbstractMessageProcessor.executeAction(AbstractMessageProcessor.java:203)
5.: com.helger.as2lib.processor.DefaultMessageProcessor.handle(DefaultMessageProcessor.java:65)
6.: com.helger.as2lib.processor.sender.AbstractSenderModule.doResend(AbstractSenderModule.java:148)
7.: com.helger.as2lib.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:942)
8.: com.helger.as2lib.client.AS2Client.sendSynchronous(AS2Client.java:435)
9.: com.helger.as2lib.test.MainSendToMendelsonServerTest.main(MainSendToMendelsonServerTest.java:152)
2021-02-09 13:29:17,398 ERROR [main] (MainSendToMendelsonServerTest:157) -  --------------------------------------------------------------------------

Do you know how to fix this issue?
Thanks,
Itay

**Comment by phax** [comment]
That depends on your VPN setup. Check your VPN gateway for specific firewall rules. Sometimes access to the Internet is not allowed while you are in VPN. Best to contact your VPN operations guys.
Maybe it's just an ackward port and only 443 would be allowed? No idea. Maybe the other side is rejecting your message, because your outgoing IP address changed or you are sending a different client certificate? So many options ;-)

Try telnetting to the other side and see if that works - if yes, than they are rejecting your message. If no, search on your side.

**Comment by ihudedi** [comment]
Hi @phax 
What host should I check?
The server is http://testas2.mendelson-e-c.com:8080/as2/HttpReceiver
what to check on telnet?
I tried telnet testas2.mendelson-e-c.com with no sucess
Thanks,
Itay

**Comment by ihudedi** [comment]
Hi @phax 
I checked it is working via https://testas2.mendelson-e-c.com:8444/as2/HttpReceiver
https is working with vpn http not
Thanks,
Itay

**Comment by phax** [comment]
Okay, so it seems like your VPN is not allowing http connections to the outside. Good to know ;-)
