### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by joris77** [phax/as2-lib#128]
Hi,

I read a large part of the documentation, but I do not see a getting started anywhere. I am able to run the spring boot demo locally, but miss a pointer on how to send a valid message there from my local machine.

Tnx in advance,

Joris Wijlens

**Comment by joris77** [comment]
I mean the first indeed :) What do you mean by included? I guess when I start with that with my project I cannot upgrade versions by just changing a version in the pom right?

**Comment by phax** [comment]
Yes okay got it.
Than the "MainSendToMendelsonTestServer" is a good starting point. Key programming action will be to get the certificates from a secure store as I assume they will not be lying around as P12 or JKS files.
The rest can easily be customized.

For the receiver part use Spring Boot as the basis. There, the CertificateFactory (see config.xml) also needs to be adopted to read the JKS/P12 data from an alternate stream.

hth
