### ISSUE TITLE
partnership  attribute: remove_cms_algorithm_protection_attrib

### ISSUE THREAD

**Issue by dang-osu** [phax/as2-lib#137]
Hello @phax 

I am working on a project that is using the AS2Client from your as2-lib...one of the attributes I need to set is the remove_cms_algorithm_protection_attrib to support a partners using IBM Sterling - AS2 server.   Do you know how this can be accomplished with the AS2Client?

**Comment by phax** [comment]
The attribute is called `remove_cms_algorithm_protect_attr`, must be set to `false` and will be available in release 4.10.1
