### ISSUE TITLE
latest certificates from keystore is not fetching when service is running

### ISSUE THREAD

**Issue by punithdj** [phax/as2-lib#144]
Hi Philip,

We  have a problem that , when service is running and if I update the  key store with new certificates , its not reflecting for incoming messages. Still it fetching from cache memory i.e old certificates and throws certificate not found exception.

**Comment by phax** [comment]
Yes, that is correct. By default the KeyStore is not reinitialized every time but only on startup.
The respective method to do so is `CertificateFactory.reinitKeyStore ()`.
Depending on how you initialize your certificateFactory you need to call the method accordingly.

**Comment by punithdj** [comment]
Thank you Philip :)
