### ISSUE TITLE
Advice on creating documentation

### ISSUE THREAD

**Issue by ChirsGod** [phax/as2-lib#145]
Hi, dear author, this project is very good, but unfortunately for people like me who don't know the as2 protocol for beginners, your project is very difficult for me to understand. Could you please take your precious time to write some documents about generating the certificate and then configuring the certificate to the SpringBoot project, the information and files of the implementation server level and the client are transferred to each other. I feel that the official description of the django-pyas2 project is very good, but our company requires that java must be used to complete this thing, so I took the liberty to raise this issue with you.

**Comment by phax** [comment]
Yes I am aware, that the information "can be extended" ;-)
I originally forked OpenAS2 because I needed it for usage in the Peppol project. Peppol now has moved towards AS4 so my personal interest in AS2 dropped a bit ;-)

Nevertheless I see your point :) If you have some specific information or table of contents of stuff that interests you, just let me know. Btw. the Wiki should be public so you are even able to provide the information "in place" :)

**Comment by ChirsGod** [comment]
Hello author, may I ask how similar this project is:[](https://django-pyas2.readthedocs.io/en/latest/quickstart.html), quickly build two test cases that can be transmitted to each other based on the AS2 protocol.

**Comment by phax** [comment]
Hi @ChirsGod, unfortunately I don't have the time to do this for you and my Python knowledge is basically zero.
May I suggest you look at the test class mentioned at https://github.com/phax/as2-lib/wiki/Sending-AS2-Messages and make the modifications accordingly?
BR, Philip

**Comment by ChirsGod** [comment]
Excuse me, your latest project will report an error when executing the build of maven. Am I missing something? My running environment is: JDK 17, Maven 3.9 
<img width="367" alt="1678248483532" src="https://user-images.githubusercontent.com/50586375/223617291-c563f789-a733-49c5-bd83-cc297a4fc692.png">

**Comment by phax** [comment]
Hi @ChirsGod, the latest version (5.1.0) requires Java 11 as the minimum. The last version that was compatible with Java 8 was 4.11.0.
See page https://github.com/phax/as2-lib/wiki/Building for the information on building the sources

**Comment by phax** [comment]
I am building with this setup without problems:
![grafik](https://user-images.githubusercontent.com/196219/223650556-700e276e-3fae-44ca-8c31-e9d730c4217f.png)
