### ISSUE TITLE
Can't work with AS2 version 5.0 with bc-fips

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#146]
Hi @phax
Until version 5.0 I could use working with BC or BCFIPS.
From version 5.0 The files working only with BC.
For Example
BCCryptoHelper::decrypt
      final SMIMEEnvelopedParser aEnvelope = new SMIMEEnvelopedParser (aPart);
aPart is from type jakarta.mail.internet.MimeBodyPart and not javax.mail.internet
In BCFIPS we work with javax.mail.internet so this version not relevant when using BCFIPS
Thanks,
Itay

**Comment by ihudedi** [comment]
Hi @phax 
Did you see my concern?
Seems I can't upgrade to latest version from version 5.
Thanks,
Itay

**Comment by phax** [comment]
If you rely on `javax.mail` then you cannot upgrade to 5.0, because that requires on the libraries with the `jakarta.mail` API - sorry.

**Comment by phax** [comment]
There is now a `bcjmail-fips` JAR that you should be able to use with as2-lib 5.x
