### ISSUE TITLE
Original message

### ISSUE THREAD

**Issue by mayousheng** [phax/as2-lib#150]
Dear Philip,
   I want to get the original message of AS2Message, how should I get it?

Thanks,

**Comment by phax** [comment]
What do you mean the "original" message?
Do you mean 
a) the message how it is transmitted on the network level or
b) the source message of an MDN?

**Comment by mayousheng** [comment]
Dear Philip,

I'm sorry I wasn't clear.

I want to get the http message information of as2 request.  This should be a)

It should look something like this

![Snipaste_2024-07-01_20-00-20](https://github.com/phax/as2-lib/assets/59812595/830c7275-ed47-4af6-9dad-8a6817cdb614)

**Comment by mayousheng** [comment]
The following lines in the `AS2SenderModule `caught my attention. Perhaps I can find the desired message here?
```
![Snipaste_2024-07-02_00-48-18](https://github.com/phax/as2-lib/assets/59812595/2cce9876-bef4-4966-a706-4359992faf64)


```

**Comment by mayousheng** [comment]
I noticed these two lines in the `AS2SenderModule`. Maybe I can get the message I need here?

![Uploading Snipaste_2024-07-02_00-48-18.png…]()

**Comment by mayousheng** [comment]
The following lines in the `AS2SenderModule `caught my attention. Perhaps I can find the desired message here?

![Snipaste_2024-07-02_00-48-18](https://github.com/phax/as2-lib/assets/59812595/61baafd8-5fb9-455f-b16d-20f3e2582559)

**Comment by phax** [comment]
I added the interfaces `IHTTPOutgoingDumper` and `IHTTPIncomingDumper` to exactly perform these issues.
For sending messages, you can provide these dumpers via the `AS2ClientSettings` class.
For receiving, you need to adopt the `AS2ReceiveXServlet....` handler accordingly (or set the dumper globally via `HTTPHelper.setHTTPIncomingDumperFactory`)

**Comment by mayousheng** [comment]
ok, I tried it this way and it worked for me.
Thank you for your help
