### ISSUE TITLE
 long form definite-length more than 31 bits

### ISSUE THREAD

**Issue by EvanZengjl** [phax/as2-lib#152]
Hello phax ,

When I test how to send message to openAS2 flowing the demo "[MainTestClient.java](https://github.com/phax/as2-server/blob/master/src/test/java/com/helger/as2/test/MainTestClient.java)"，
it occuer the error 
”com.helger.as2lib.exception.WrappedAS2Exception: java.io.IOException: long form definite-length more than 31 bits“ 。
why this happen?

**Comment by phax** [comment]
Well, I recommend you use e.g `MainSendToMendelsonTestServer` for testing towards the Mendelson test server.

Your specific error message indicates the usage of EC certificates. Is it true?

**Comment by phax** [comment]
Closing this issue due to lack of information. Feel free to re-open when more information is available
