### ISSUE TITLE
Insecure SSL configuration in AbstractHttpSenderModule

### ISSUE THREAD

**Issue by EdMcBane** [phax/as2-lib#20]
I've noticed that the SSL configuration in AbstractHttpSenderModule is insecure, in that it does not verify certificates or hostames (using DoNothingTrustManager and HostnameVerifierAlwaysTrue).
Moreover, there seem to be no obvious way to override these when used from AS2ClientBuilder / AS2Client, since AS2Client.sendSynchronous() does instantiate an insecure AS2SenderModule directly, without any factory or configuration point.
Is this by design? Would you accept a pull request that made the AS2SenderModule configurable?

Cheers

**Comment by phax** [comment]
Thanks for pointing this out.
Any PR is welcome :)

**Comment by phax** [comment]
Thanks for PR #21

**Comment by phax** [comment]
The commit adds 2 additional protected methods that allows you to customize `SSLContext` and `HostnameVerifier`. Does that make adaptation more simple?

**Comment by EdMcBane** [comment]
Indeed. Thanks.

**Comment by phax** [comment]
You want a 2.2.8 release

**Comment by phax** [comment]
Release 2.2.8 is out
