### ISSUE TITLE
Support dumping of sent HTTP request

### ISSUE THREAD

**Issue by mzapletal** [phax/as2-lib#26]
It would be nice to support easy dumping of the sent AS2/HTTP request. I have seen corresponding code doing this, but the code is currently "locked" by this flag (https://github.com/phax/as2-lib/blob/master/as2-lib/src/main/java/com/helger/as2lib/processor/sender/AS2SenderModule.java#L105)

**Comment by phax** [comment]
Class 'HTTPHelper' has now methods 'setHTTPIncomingDumper' and 'setHTTPOutgoingDumper' to set custom callbacks.
Can you please verify it with SNAPSHOT >= 8 from https://oss.sonatype.org/content/repositories/snapshots/com/helger/as2-lib/3.0.1-SNAPSHOT/ - thanks :)

**Comment by phax** [comment]
Release 3.0.1 is in approx. 30 minutes on Maven Central
