### ISSUE TITLE
List of variable that can be used in "as2-servlet-configuration.xml"

### ISSUE THREAD

**Issue by haegg78** [phax/as2-lib#27]
I have currently implemented the AS2 Servlet in a test suite where we are performing regression testing of our integration platform. I'm wondering which parameters are existing for generating a better dynamic filename? I'm specifically interested in the AS2 Filename and AS2 Subject. Example from the readme below. Is there a list of "variables" that can be used in the "as2-servlet-configuration.xml" file?
`<module classname="com.helger.as2lib.processor.storage.MessageFileModule"
            filename="%home%/inbox/$date.yyyy$/$date.MM$/$msg.sender.as2_id$-$msg.receiver.as2_id$-$msg.headers.message-id$"
            header="%home%/inbox/msgheaders/$date.yyyy$/$date.MM$/$msg.sender.as2_id$-$msg.receiver.as2_id$-$msg.headers.message-id$"    
            protocol="as2"
            tempdir="%home%/temp"/>`

**Comment by phax** [comment]
For incoming messages the following variables are available:

  * `date` - everything after the dot is used as the SimpleDateFormat formatting (see class `DateParameters`)
  * `msg` - message related parameters. The part between the dots can be:
    * `sender` - message sender ID
    * `receiver` - message receiver ID
    * `attributes` - message attributes - access to all internal message attributes
    * `headers` - message headers - access to all message headers
    * `content-disposition` - supports only the sub-value `filename`

https://github.com/phax/as2-server/blob/master/doc/configurationDefinitions.html contains the original docs with some infos.

hth
