### ISSUE TITLE
Async MDN support for AS2Client

### ISSUE THREAD

**Issue by xloggerster** [phax/as2-lib#31]
It seems like com.helger.as2lib.client.AS2Client only support AS2 message sending using synchronize MDN mode (through sendSynchronous() method). Is it possible to use this client to send AS2 in Asynchronized MDN mode instead?

I tried to read the source code and seems like async or not was controlled by aPartnership.setAS2ReceiptOption ()... what value should be set for this option value in order to support async MDN? any other changes needed?

**Comment by phax** [comment]
To send an async MDN you need a server component, whereas the AS2Client is meant to operate on a "library" basis, without a required server component. I will try to figure out the required parameters and make the needed changes. May take some days - I'm currently ill :(

**Comment by phax** [comment]
Oops - I totally missed that one :(

**Comment by phax** [comment]
`AS2ClientSettings.setAsyncMDNUrl (String)` should do the trick. Is contained in v3.0.4 release that is build now
