### ISSUE TITLE
Large files

### ISSUE THREAD

**Issue by zharpaz** [phax/as2-lib#37]
Hi Philip,

It seems that the issue with large files comes from HttpUrlConnection. The OutputStream that is obtained from it stores all data in memory and only at the end writes it to the socket. I would like to add the possibility to work with Apache HttpClient that supports streaming without holding all data in memory.
What do you think?
Thanks,
  Ziv

**Comment by phax** [comment]
Hi Ziv,
in general this is a good idea, and I already tried that myself. The issue is, the "socket only" connection currently used from the "as2-server". That most likely implies huge changes there as well.
// Philip

**Comment by zharpaz** [comment]
I see...
I will look at receiving in a servlet environment, and then decide how to continue with this.
