### ISSUE TITLE
Disposition-notification-to header

### ISSUE THREAD

**Issue by zharpaz** [phax/as2-lib#42]
Hi Philip,

Looking at the headers of the message, I do not see the "Disposition-notification-to=email@acme.com" header. I thought it should be included in the message to signal that an MDN is required.

Thanks,
  Ziv

**Comment by phax** [comment]
Indeed it is. But it must be part of the partnership.
It is applied here: https://github.com/phax/as2-lib/blob/master/as2-lib/src/main/java/com/helger/as2lib/processor/sender/AS2SenderModule.java#L446

hth, Philip

**Comment by zharpaz** [comment]
I see. What about the option of working synchronously, but not asking for MDN?

Thanks,
  Ziv

**Comment by phax** [comment]
If you mean you don't want an MDN - just do not send the header. As you can see in the code - if the partnership does not have the property, that header is not send, and no MDN is requested.
If you want an async MDN, add more headers.

**Comment by phax** [comment]
If you don't want an MDN, don't send the header. As you can see in the code, the header is only set, if the respective field of the partnership is present. If the header is not send, you will hopefully only get an HTTP status code back. Did I understand your requirement correctly?

**Comment by zharpaz** [comment]
Hi,
when a message does not contain "Disposition-notification-to", and does contain the header "Disposition-Notification-Options", the server does return an MDN. (com.helger.as2lib.message.AS2Message#isRequestingMDN, line 106).
Does it conform to the standard?
(if I do not send it, I get the error 'The value of 'DigestAlgorithm' may not be null').

Thanks for your help,
  Ziv

**Comment by zharpaz** [comment]
My understanding from the RFC is that if the header Disposition-Notification-To does not exist, an MDN should not be returned. Currently the server returns an MDN when Disposition-Notification-Options exists.

The result is that I cannot make the client generate a message that does not receive an MDN (without asynchronous reply).

**Comment by phax** [comment]
It is already deleted in master branch. Please check the Snapshot version and tell me if it works.
I'm on vacation for one week so I will not respond.

**Comment by open-gdsn** [comment]
We are currently looking into use AS2-Lib as a replacement of our (previously certified) AS2 software. What should be kept in mind regarding interoperability is that in some case, the implementations of the certified software deviates from the specs if all certifying parties agreed on that in the certification process. Iirc (did not work here when the software was certified), these Drummond certification tests and reports can be found on the internet.

**Comment by phax** [comment]
@open-gdsn I'm aware of this, that's why I changed this. I just forked the project, because I needed an AS2 solution and OpenAS2 development was stalled. I updated the software so that it works for me (in the PEPPOL context) and for the rest I'm relying on community input.
So everytime you find an incompatibility just let me know. As an individual not having the resources to perform Drummond testing :(
Btw. I did not release a new version, because @zharpaz is building a PR with large file support which I want to investigate before releasing.

**Comment by open-gdsn** [comment]
Sorry, I now see I used my 'wrong' GitHub account, my name is Ronald van Kuijk, usually using '@Kukel' (nickname) as Gitbub account. I'll keep monitoring things ;-)

**Comment by phax** [comment]
I think it has been tested thoroughly and will be included in the 4.1.1 release

**Comment by kukel** [comment]
The value of the AS2MDNTo should (according to the specs) be in RFC2822 format and hence not being the AS2ID!. Although the spec also states that receiving systems should be very lenient, it is better to try to adhere to the specs.


> 7.3.  Requesting a Signed Receipt
> 
>    Message disposition notifications are requested as per RFC 3798.  A
>    request that the receiving user agent issue a message disposition
>    notification is made by placing the following header into the message
>    to be sent:
> 
>         MDN-request-header = "Disposition-notification-to"
>                             ":"  mail-address
> 
>    The following example is for requesting an MDN:
> 
>         Disposition-notification-to: xxx@example.com
> 
>    This syntax is a residue of the use of MDNs using SMTP transfer.
>    Because this specification is adjusting the functionality from SMTP
>    to HTTP while retaining as much as possible from the [4]
>    functionality, the mail-address MUST be present.  The mail-address
>    field is specified as an RFC 2822 localpart@domain [addr-spec]
>    address.  However, the address is not used to identify where to
>    return the MDN.  Receiving applications MUST ignore the value and
>    MUST not complain about RFC 2822 address syntax violations.

**Comment by phax** [comment]
Next try :)
