### ISSUE TITLE
as2-servlet: JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by yusufbata** [phax/as2-lib#49]
I'm getting the following error when trying to receive a message using as2-servlet:

`ERROR [com.helger.as2lib.processor.receiver.net.AS2ReceiverHandler] (default task-8) Error decrypting  [<MY-JUNIT-TEST-CASE-phax-as2-lib-31072018232014+0200-1843@OpenAS2B_OID_OpenAS2A_OID>]: JCE cannot authenticate the provider BC`

I've tried a number of options found online without any success. Any ideas on how to resolve this?

Thanks!
Yusuf

**Comment by phax** [comment]
Hi. I'm on vacation this week so I only have quick ideas: is BouncyCastle in your classpath? If yes which version? The latest version of BC is 1.60.
Hth Philip

**Comment by yusufbata** [comment]
Thanks for the quick reply!

I've packaged BouncyCastle version 1.59, as well as 1.60 - same issue occurs with both.

Do you have a working example project that contains as2-servlet (i.e. a deployable war)?

Thanks!
Yusuf

**Comment by phax** [comment]
What does packaged mean?  Maven assembly plugin and BC does not work, because BC is a signed JAR! Also uberjar and all that stuff must be handled with care. A sgandalone example for using as2-servlet is available and will be published after my vacation next week. So stay tuned

**Comment by phax** [comment]
Did the hint on packaging help you? Did this solve your issue?
https://vzurczak.wordpress.com/2017/09/04/bouncycastle-osgi-and-uber-jars/ contains the explanation.
Try e.g. https://stackoverflow.com/questions/17658831/how-can-i-exclude-dsa-and-sf-files-from-shaded-jar for a possibility to exclude *.SF, *.DSA,*.RSA

**Comment by yusufbata** [comment]
Thanks Philip - excluded the bouncy castle dependencies from the war and its working perfectly.

**Comment by phax** [comment]
Great that it works :)
