### ISSUE TITLE
Need clarification regarding mdnoptions - signed/unsigned mdn

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#56]
Hi Philip,
I would like to know what the correct value for mdnoptions when mdn needs to be signed and not signed.
In my code when mdn not signed I set the protocol algorithm to null and set protocol imprtance and mic algorithm importance to optional while in signed mdn I set all importance to required and set the protocol algorithm.
Is it the correct behaviour?
Thanks,
Itay

**Comment by ihudedi** [comment]
I didn't understand this solution is for unsigned mdn? Can we send null in mdnoptions?

**Comment by phax** [comment]
No, when sending `null` it falls back to the default (signed, SHA1).
You need to explicit send `""` to state: don't use default.... It's a legacy default.

**Comment by ihudedi** [comment]
I meant setting null in as2clientsetting.setmdnoptions((String)null)

**Comment by ihudedi** [comment]
I didn't understand.for not requested mdn I set null and for unsigned I set "".?

**Comment by phax** [comment]
To overall request and MDN or not, you use the method `setMDNRequested (boolean)` from the `AS2ClientSettings` class.
By default the requested MDN is signed. To disable this signing use `setMDNOptions ("")`.
Ok?

**Comment by ihudedi** [comment]
If I set to null is it also fine? For not sending mdn do i need to set the mdniptions too?

**Comment by phax** [comment]
Okay, I modified the implementation, so that MDNOptions can also be `null` :)

**Comment by ihudedi** [comment]
10x:)
