### ISSUE TITLE
When mdn isn't requested no need to calculate mic

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#58]
Hi Philip,
When working with not mdn you don't need to calculare mic.
Is It redundant?
Thanks,
Itay

**Comment by phax** [comment]
Correct, but just a minimal overhead....

**Comment by ihudedi** [comment]
Adding check for requsetmdn will save the calculation.

**Comment by phax** [comment]
I'm not sure if the MIC is really only used if a signed MDN is requested, or else as well. I need to check with the specs.

**Comment by ihudedi** [comment]
I am talking when not requesting mdn.

**Comment by phax** [comment]
Done :)
