### ISSUE TITLE
Sync mdn - if mic isn't matched excetiopn isn't thrown

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#59]
Hi Philip,
When working with sync mdn and the mic that returned from the server doesn't match the mic calculated in the client the as2 lib only print that the mic isn't matched without throwing exception.
Is it desired behaviour?
Thanks,
Itay

**Comment by phax** [comment]
Yes it is.
Basically because there a lot of different algorithms out there.
But maybe a callback handler to handle "MIC not matched" would potentially make sense :)

**Comment by ihudedi** [comment]
But in astbc mdn if mic isnt matched you return false for the checking

**Comment by phax** [comment]
Finally a new interface `IMICMatchingHandler` that can be used to customize the MIC match and mismatch handling; part of 4.4.0 release
