### ISSUE TITLE
Inconsistent API in Partnership

### ISSUE THREAD

**Issue by jochenberger** [phax/as2-lib#6]
This is a very minor issue, but it somehow feels strange this way.
`Partnership.getAllAttributes()` returns `IStringMap` whereas `getAllSenderIDs()` and `getAllReceiverIDs` return `StringMap`. I'd say they should all return `IStringMap`.
But maybe the methods should be deprecated altogether and replaced by getters and setters for each property, but I guess that's a separate issue.

**Comment by jochenberger** [comment]
One more thing:
there's `addAllAttributes(IStringMap)` but `addSenderIDs(Map<String,String>)` and `addReceiverIDs(Map<String,String>)`, so different parameter type and different naming scheme.

**Comment by phax** [comment]
Thanks for pointing that out Jochen. Indeed minor things, but still important :)
