### ISSUE TITLE
PBCProvider - Ability to use FIPS mode only - create provide using reflection

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#65]
Hi Philip,
AS2-LIB now support BC & BCFIPS provider but you must have BC 1.60 in your class-path.
Our code support only BC FIPS and I would like that PBCProvider will add the provider at runtime according to the provider name that can be changed via setter method.
The code in PBCProvider  is hardcoded.In case the provider doesn't exist you create the Provider by calling the BC provider constructor.( new BouncyCastleProvider)
I am asking if you can change this file to create the provider using reflection and for default it will create that BC provider using the full package and for BCFIPS provider it will create via reflection.
You can add setter method of the provider package path or by the provider name and set the provider in if condition.
I would be grateful if you can modify this code for 4.2.0
Thanks,
Itay

**Comment by phax** [comment]
SNAPSHOT build is currently worked on by Travis - please cross check

**Comment by phax** [comment]
But anyway you may need to add the `<exclude>` statement in your POM to exclude regular BC

**Comment by ihudedi** [comment]
Hi Philip,
Thanks for the fix.
I already excluded BC from my pom.
Thanks a lot,
Itay

**Comment by ihudedi** [comment]
Hi Philip,
Do you have any estimation when 4.2.0 will be release?
Thanks again,
Itay

**Comment by phax** [comment]
So the fix works for you?

**Comment by ihudedi** [comment]
Yes.
Thanks for the quick response.
Itay
