### ISSUE TITLE
MIC isn't matched when using compress before signing flag 

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#68]
Hi Philip,
When using compressBeforeSigning flag (settings.setCompress(type,true) the following actions are performed for the message in AS2SenderModule:
compress
sign
encrypt

but in AS2ReceiverHandler  we are doing:
decrypt
compress
verify

and the mic isn't matched because the data isn't the same.
if I change to use compress after sign as:
sign
compress
encrypt

then the mic is matched.

Is it bug ? or need to add parameters to check if aPartnership.isCompressBeforeSign () and perfom the same logic as we do in send message.I am not sure if all params are set in the partnership there and maybe needs to pass them via headers/attributes of the message to the partnership object.

Thanks,
Itay

**Comment by phax** [comment]
That setting is there to support legacy AS2 systems. The default value `true` should match the default setup.
Just change this if your partner does it incorrectly...

**Comment by ihudedi** [comment]
I am using the client server of as2 library and it isn't working.

**Comment by phax** [comment]
So you mean the documentation is invalid and should be updated?

**Comment by ihudedi** [comment]
I mean you have 2 cases in compress before and after the sign and you handle it client but in server you support only compress after sign.maybe adding attribute to config.xml and handle in recieverhandler.

**Comment by ihudedi** [comment]
Hi Philip,
I run the medelson test with compress before sign and after sign and the MIC is matched for the 2 cases against mendleson test server.Look like there is an issue with AS2 server with MIC calculation.
For now only the compress after sign is working against AS2 server.
Thanks,
Itay

**Comment by ihudedi** [comment]
Do you have an idea how mendelson server calculate mic for both cases and its matched to the mic calculate in client while as2 server failed?

**Comment by phax** [comment]
Hi. I have no idea how Mendelson does it. I want to check the specifications first before making a decision here :)

**Comment by phax** [comment]
I checked with the latest version (4.4) - MIC is matched in both cases

**Comment by camiloh** [comment]
I've had the same issue where the MIC generated by as2-lib server does not match what the sender expects when compression is on but it does match when compression is off. I've tested with both mendelson AS2 and SAP B2B Toolkit 2.0 as the sender and both had the same issue.

**Comment by phax** [comment]
@camiloh  if this is an issue, please open a new request and add some details (like version, standalone or as servlet) etc. Thanks :)
