### ISSUE TITLE
Mendelson Test is not working

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#69]
Hi Philip,
When I run the mendelson test with correct ancryption and signature (SHA_1 and 3DES) 
I am always getting connection reset while the mendelson server is up.
Do you know why?

**Comment by phax** [comment]
No idea. Do you have a proxy in use? I never run the Mendelson server locally. Sorry

**Comment by phax** [comment]
https://stackoverflow.com/questions/62929/java-net-socketexception-connection-reset maybe a good starting point for observations

**Comment by ihudedi** [comment]
It was working awhile ago but now it stopped working.If I send empty post message from http client I am getting 400 error code.So it seems it is working but not for sending as2 messages.

**Comment by phax** [comment]
I just tested out of the box `MainSendToMendelsonTestServer` application and it is working flawlessly. Did you enable large file support or did you take it as it is?

**Comment by ihudedi** [comment]
I run it as is with no change.How can I know I am running behind proxy?

**Comment by ihudedi** [comment]
Hi philip,
I run the mendelson test via my wifi hot spot and it's working fine.Seems like an issue in my company.

**Comment by phax** [comment]
Ah okay. So it was effectively a "bad request" :)
What was the "incorrect format" you mentioned above?
Sorry for being quite unresponsive atm - will get better in October again

**Comment by ihudedi** [comment]
I tried to run post message against mendelson test server but I didn't give all headers and body and return me 400 code.
I don't know why it isnt working from my company.maybe firewall but when trying connect to mendelson via browser he returned get method isnt correct.so the connection fine but with all as2 message he failed with connection reset.
