### ISSUE TITLE
Content-Transfter-Encoding not specified in headers

### ISSUE THREAD

**Issue by keithveeva** [phax/as2-lib#71]
Hi Pillip,

Our project uses your as2-lib core library to handle our AS2 communication and we cannot seem to be able to send the Content-Transfter-Encoding header (CTE) in our message. We set it explicitly in our message and it looks to be picked up by your code, but digging into the underlying sdk call it looks like this header is on a list of restricted headers, can you confirm if this is the case or how can we enable this in your library? Looking at the sdk code this is controlled by a system property, ideally we would like to NOT turn this system property on, please let me know if there are any other options.

Thanks,
Keith

**Comment by phax** [comment]
Hi Keith,
I'm aware of this situation, as I myself was struggeling with that.
That is one of the reasons I didn't release 4.2.0 yet.
The Content-Transfer-Encoding (CTE) can basically be set for the payload as well as for the certificate part.
Unfortunately when using encryption it seems like the CTE is not properly honored from within BC (or at least I didn't find out how).
It would be great if you could confirm that this only affects encrypted messages.
Thanks, Philip

**Comment by keithveeva** [comment]
Hi Phillip,

We have a requirement to use only encrypted messages so I didn't test
unencrypted messages.
Looking at the SDK, I'm not sure you can set this header without setting
the system property, can you please confirm?

Thanks,
Keith

**Comment by keithveeva** [comment]
Also we're using version 3.1.0, let me know if the later versions would
address this issue.

Thanks,
Keith

**Comment by phax** [comment]
I assume you refer to `AS2ClientRequest.setContentTransferEncoding` which was introduced in 3.0.4.
And this is exactly what is not working properly in all cases :(

**Comment by keithveeva** [comment]
I'm looking at this stack

HttpURLConnection#setRequestProperty *-> *if you look at this method, it
checks if a header is restricted and CTE is on that list, which prevents it
from getting set and sent.
AS2HttpHeaderWrapperHttpURLConnection#setHttpHeader
AS2SenderModule#updateHttpHeaders
AS2SenderModule#_sendViaHTTP
AS2SenderModule#handle
AS2Client#sendSynchronous

**Comment by keithveeva** [comment]
Looking at the headers generated, since we encrypt the message, it's NOT
generated as a multipart message, its content type is not multipart message.

**Comment by phax** [comment]
Hi Keith,
I think I found the reason, it just takes a bit to implement everything.
The current situation is a bit of a mess, because the current version contains old "HttpUrlConnection" as well as mew "HttpClient" based implementations in parallel.
So I need to fix it for both, release 4.2.0 and than get rid of the old version.
// Philip

**Comment by keithveeva** [comment]
Hi Phillip,

Sounds great! I was suspecting the version of HttpURLConnection maybe
outdated, but wanted to consult you as you're the expert of this code.
For release 4.2.0, is it possible to squeeze in the enhancement I logged in
https://github.com/phax/as2-lib/issues/70? If you can expose a way to
specify the chunk length in the AS2ClientRequest or AS2ClientSettings object
that'd be great.
Currently we have to make a fork of your code and make this change on our
end, if you can squeeze it in release 4.2.0 then we can get rid of our fork.

Thanks,
Keith

**Comment by phax** [comment]
So it took some time but I finally managed to get the Content-Transfer-Encoding thing working. It works at least with the new "large file support" version based on Apache HTTP Client. I'm still struggeling with the old "HttpURLConnection" version, because of this "forbidden header" thingy.
The workaround according to https://bugs.openjdk.java.net/browse/JDK-6996110 is to specify the system property `-Dsun.net.http.allowRestrictedHeaders=true` on the commandline.

**Comment by phax** [comment]
Additionally "compress before signing" does not work with Content-Transfer-Encoding other than "binary". I'm investigating this

**Comment by phax** [comment]
With #87 the `HttpUrlConnection` is gone

**Comment by phax** [comment]
Now the CTE can be set and the MIC calculation is consistent with the one from Mendelson
