### ISSUE TITLE
Request - add original MIC to message attributes

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#74]
Hi Philip,
In receiveSyncMDN of AS2SenderModule
Could you please add this line:
aMsg.attrs().put(AS2MessageMDN.MDNA_MIC,sOriginalMIC);
I would like to get MIC via message.
Thanks,
Itay

**Comment by phax** [comment]
The constant with the name is `AS2Message.ATTRIBUTE_MIC`
