### ISSUE TITLE
DefaultMessageProcessor threw exception(s): javax.mail.MessagingException: Missing start boundary

### ISSUE THREAD

**Issue by atlazfin** [phax/as2-lib#82]
Hello,

I am sorry to bother, but i am in a kinky situation. I have an AS2 server built on phpas2. I am able to receive messages from our partner and i am able to generate the mdn and send it. It seems that the MDN is not readable in the openas2-server by the sender.

The sender is not willing to debug this problem and i have no idea where the fault is.

So 
1) I am able to receive and process the as2-messages the sender sends me
2) I am generating a SYNC mdn
3) Sender cannot process mdn, resends the original as2-message 10 times.

```
The error the sender provides me is:
"VirheProcessor 'DefaultMessageProcessor threw exception(s): javax.mail.MessagingException: Missing start boundary

Tarkempi virhecom.helger.as2lib.processor.ProcessorException: Processor 'DefaultMessageProcessor threw exception(s): javax.mail.MessagingException: Missing start boundary at com.helger.as2lib.processor.DefaultMessageProcessor.handle(DefaultMessageProcessor.java:140) at fi.solita.golli.service.edi.InterchangeProcessingService.lambda$handleOutgoingInterchange$402(InterchangeProcessingService.java:157) at fi.solita.golli.service.edi.InterchangeProcessingService$$Lambda$177/519923357.process(Unknown Source) at fi.solita.golli.service.edi.InterchangeService.process(InterchangeService.java:90) at fi.solita.golli.service.edi.InterchangeService$$FastClassBySpringCGLIB$$fad53b90.invoke(<generated>) at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:718) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) at org.s"
```

The MDN-message i _think_ i am sending, is as follows: 

```
Message-ID: <2019-03-06-5c7f8379337562.77043407@OURSERVER.xxx.fi>
Date: Wed, 06 Mar 2019 08:23:21 +0000
Ediint-Features: CEM
AS2-From: OURSERVER
AS2-To: SENDERSERVER
AS2-Version: 1.2
User-Agent: PHPAS2
Connection: close
MIME-Version: 1.0
Content-Type: multipart/signed; protocol="application/pkcs7-signature"; micalg="sha-256"; boundary="----BE4C04A28692FEDCF17827A1E6154AF0"

------BE4C04A28692FEDCF17827A1E6154AF0
Content-Type: multipart/report; report-type=disposition-notification; boundary="----=_7577f4bd8e7c7475a2c1a50dcfc64bfd1068765c"

------=_7577f4bd8e7c7475a2c1a50dcfc64bfd1068765c
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

The AS2 message has been received
------=_7577f4bd8e7c7475a2c1a50dcfc64bfd1068765c
Content-Type: message/disposition-notification
Content-Transfer-Encoding: 7bit

Reporting-UA: PHPAS2
Original-Recipient: rfc822; OURSERVER
Final-Recipient: rfc822; OURSERVER
Original-Message-ID: <ph-OpenAS2-06032019094040+0200-7019@SENDERSERVER_OURSERVER>
Disposition: automatic-action/MDN-sent-automatically; processed
Received-Content-MIC: QPbpZwm/oIyZqsBcuNplJjacAok=, sha1

------=_7577f4bd8e7c7475a2c1a50dcfc64bfd1068765c--

------BE4C04A28692FEDCF17827A1E6154AF0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7s"
Content-Type: application/pkcs7-signature; name=smime.p7s; smime-type=signed-data

MIIJwAYJKoZIh....truncated...

------BE4C04A28692FEDCF17827A1E6154AF0--
```

I would very much appreciate, if you could point me to the right direction...

**Comment by phax** [comment]
Hi, do you eventually have some proxy servers in between?
Please have a look at https://github.com/phax/as2-server/issues/22 - that seems kind of similar...

**Comment by atlazfin** [comment]
Hello,
I am not sure. I just did a dry POST to the sender server, and it says it is running a TEngine webserver that is based on Nginx, which seemed to be an issue in the other similare case, if i understood correctly.  I am not sure if i can do anything about this in my end, where i am sending the mdn.

br,
Petter

**Comment by phax** [comment]
Hi Petter,
okay, so there seems to be an Nginx in play here.
Let me do some changes to base libraries (a ph-commons release etc.)
Can you than test with the latest SNAPSHOT version or do you need a release?
// Philip

**Comment by atlazfin** [comment]
Hello,

Sorry for not being clear. 

I am not able to work with the sender, who is apparently using openAS2 to receive my MDN and failing with the missing boundaries error.  

I am using phpas2 to receive the messages from the senders system and then sending the SYNC mdn back to them using the same phpas2. I am able to receive the messages they send but when i try to send the MDN it apparently fails and their server tries to resend the same message 10 times, since it hasn't been able to verify, that i have received the messages.

I do not think there is much you can do, but i am mostly looking for sympathy and pointers to what could generate the errors in our partners end, since they are not willing too look into this themselves. It could well be, that the phpas2-library is doing something fishy, that breaks the openas2-server. 

When comparing headers, i've noticed that phpas2 encloses the algo with "" ( micalg="sha-256"; ) where the examplefiles i have seen are without quotes ( micalg=sha-256;). I do not know if this could have any problems.

**Comment by phax** [comment]
Ah okay :) Now I got it. I have a software called "ph-as4" and I thought you have a typo referening to this lib as "phpas2" instead of "ph-as2" :D - but now I got it.

I don't know if quotes create an error... This needs separate investigation.
Ensure all HTTP header lines are in one row - no line breaks there.

What strikes me, is the "double" mimeyfication:
```
Content-Type: multipart/signed; protocol="application/pkcs7-signature"; micalg="sha-256"; boundary="----BE4C04A28692FEDCF17827A1E6154AF0"

------BE4C04A28692FEDCF17827A1E6154AF0
Content-Type: multipart/report; report-type=disposition-notification; boundary="----=_7577f4bd8e7c7475a2c1a50dcfc64bfd1068765c"

------=_7577f4bd8e7c7475a2c1a50dcfc64bfd1068765c
```

so there is a MIME in a MIME - usually one boundary should suffice...

hth

**Comment by phax** [comment]
So Petter, did you manage to progress here?

**Comment by atlazfin** [comment]
Hello, 
Thanks for following up. Our partner sends messages only on thursdays and won't debug this problem with me, so i've got one shot per week to try something and see if it helps. I am now  trying to see, if i can remove the secondary "mimeyfication" and trying to unquote the micalg. I am not hopefull.

**Comment by phax** [comment]
But you would be able to send something to me right?

**Comment by phax** [comment]
Or try sending to Mendelson demo server at http://testas2.mendelson-e-c.com:8080/as2/HttpReceiver
Using `mendelsontestAS2` as as2-from and as2-to and using the certificates located at https://github.com/phax/as2-lib/tree/master/as2-lib/src/test/resources/mendelson you should be able to test sending to them

**Comment by phax** [comment]
Any news on this one? Were you able to resolve it?
