### ISSUE TITLE
Following up on Long Runnig Requests

### ISSUE THREAD

**Issue by fuzails** [phax/as2-lib#85]
We randomly still get the following:

2019-05-10 16:32:03.850 ERROR 11092 --- [RequestTrackerMonitor-1] .h.x.r.LoggingLongRunningRequestCallback : Long running request. ID=1; millisecs=31999;

We have moved all out processing of messages to run asynchronously and we use /dev/urandom fix for java on linux. The problem is this error is totally random and we dont know what causing it.

Not sure where we could look to see why requests are getting stuck.

**Comment by fuzails** [comment]
Could this be related to VerySecureRandom. Is there an option to turn off VerySecureRandom and what would be the impact?I seein as2-standalone there was anoption to turn it off.

**Comment by phax** [comment]
Hi, the long running requests can have different sources - large requests can also be some of them.
When using the latest and greatest version of the as2-lib with ph-commons 9.3.2 or later, you should see an entry in the log file stating, that VerySecureRandom (re-)initialization "took too long".
So depending on the version, I can give advice.

**Comment by phax** [comment]
With the latest 4.3.0 release, the SecureRandom stuff should be resolved
