### ISSUE TITLE
File is corrupted when sending a PDF file across using as2-lib

### ISSUE THREAD

**Issue by sheebapadma** [phax/as2-lib#89]
If an xml is sent, it works fine. the file can opened on the receiving end. But if a pdf file is sent, the file is corrupted and cannot be opened on the receiving end. 
Any help would be greatly appreciated.

**Comment by phax** [comment]
What version of as2-lib are you using?
What Content-Encoding are you using?
Are you using the "AS2Client" class?

**Comment by sheebapadma** [comment]
Sorry for the late reply.. It ended up as an issue on my side. The file was double encrypted. Its working fine now.  
we are using version 4.2.0.
