### ISSUE TITLE
MDN contains OpenAS2Exception with LF line endings in human readable text/plain element in an error case.

### ISSUE THREAD

**Issue by Shucki** [phax/as2-lib#90]
If an OpenAS2Exception occurs during DO_STORE action of an AS2Message in a module a MDN with an OpenAS2Exception inside of the human readable text is sent. The line endings of that Exception are in LF which is illegal according to https://www.ietf.org/rfc/rfc2046.txt (see 4.1.1).

**Comment by phax** [comment]
Thanks for pointing this out :)

**Comment by phax** [comment]
Hopefully I captured all cases. This will be part of the 4.4.2 release
