### ISSUE TITLE
Can't send AS2 message when the sender or reciever has space in their AS2 ID

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#92]
Hi Philip,
There is an issue that when AS2 ID contains space the AS2 LIb cut the ID like:

The AS2 ID in the header should be quoted according to the specification, and since they are not on the headers of the message received by the client, the receiving application will interpret the AS2 ID up until the first space. Then

AS2-To: Cleo; - TEST is interpreted by the receiving application as Cleo;
AS2-From: BMC AWS is interpreted by the receiving application as BMC

Could you please check this issue and if there anything to do wrkarounf until you fixed it or where to fix it.

Thanks,
Itay

**Comment by phax** [comment]
Hi @ihudedi it took some time, but I think I found a decent solution for this. I checked with RFC 2616 encoded header values and added automatic quoting if necessary. So 4.4.2 will do the trick for you.

If you are interested, the main change is in `HttpHeaderMap.getUnifiedValue` in ph-commons 9.3.6, which in turn invokes the new `RFC2616Codec` class. hth
