### ISSUE TITLE
Content type is quoted leading to boundary of multipart being double quoted

### ISSUE THREAD

**Issue by Shucki** [phax/as2-lib#95]
Since version 4.4.2 mendelson can no longer process an MDN response received. Looking at the response it seems that the boundary of the multipart is an issue.
The entire content type seems to be quoted the wrong way:
`Content-Type: "multipart/report; report-type=disposition-notification;    boundary=\"----=_Part_0_578487367.1568197726076\""` 
I have not enabled the quote header values setting.

I have not found an RFC that specifies the content type in quotes. I believe the issue is the AS2HttpHeaderSetter setting the header according to the whole value and not the contents of the value.

**Comment by phax** [comment]
Yes I noticed that myself, and that's why 4.4.3 was released - that should fix the issue.

**Comment by phax** [comment]
I just tested it and it works fine again. Sorry for any inconvenience it caused.

**Comment by Shucki** [comment]
I am still experiencing it with 4.4.3: 
```
* Done waiting for 100-continue
* We are completely uploaded and fine
< HTTP/1.1 200 OK
< AS2-To: mendelson
< AS2-From: openas2
< AS2-Version: 1.1
< Date: "Mi, 11 Sep 2019 15:00:45 +0200"
< Server: "ph-OpenAS2 4.4.3"
< Mime-Version: 1.0
< Subject: "Your Requested MDN Response"
< Content-Transfer-Encoding: binary
< Content-Type: "multipart/report; report-type=disposition-notification;    boundary=\"----=_Part_0_172702331.1568206845081\""
< Message-ID: "<ph-OpenAS2-11092019150045+0200-7071@OPENAS2_MENDELSON>"
< Content-Length: 756
```

**Comment by Shucki** [comment]
I am not getting a dump for the outgoing message (I enabled both incoming and outgoing, incoming does work but the MDN is not dumped).
I am using sync MDN, so the AS2ReceiverHandler sends the MDN in sendMDN.
With debugging I found: 
1. Line 103 call aHeaders.getAllHeaderLines(true)
2. in HttpHeaderMap line 731 getAllHeaderLines calls forEachHeaderLine
3. HttpHeaderMap forEachHeaderLine and forEachSingleHeaderLine call quoteIfNecessary with "true".
Line 701 in HTTPHeaderMap:
`final String sHeaderLine = sKey + ": " + (bUnifyValue ? getUnifiedValue (sValue, true) : sValue);`


this leads to the quoting of the content type (and other headers).

**Comment by phax** [comment]
Release 4.4.4 is out and should fix that. Sorry for inconvenience. Please confirm that it works. Thx.

**Comment by Shucki** [comment]
I can confirm that strings are no longer quoted in 4.4.4 in my case. Tested with curl and checked output manually and mendelson also works again. Thank you for the quick fix and release.

**Comment by phax** [comment]
Thanks for crosschecking :D
