### ISSUE TITLE
Async MDN isn't working in version 4.4.4 (Missing start boundary)

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#97]
Hi Philip,
When I try to perfrom async mdn I am failing in :
2019-10-07 16:05:43,199 DEBUG [AS2ConnectionThread-AS2MftMDNReceiverModule] (BCCryptoHelper:685) - BCCryptoHelper.verify; X509 subject=CN=CTM_MFT,OU=CONTROL-MaD,O=BMC Software Ltd.,L=Houston,ST=TX,C=US; useCertificateInBodyPart=true; forceVerify=false
2019-10-07 16:05:43,201 INFO [AS2ConnectionThread-AS2MftMDNReceiverModule] (OpenAS2Exception:118) - OpenAS2 NetException terminated: Address = /127.0.0.1 port = 56675
com.helger.as2lib.exception.WrappedOpenAS2Exception: javax.mail.internet.ParseException: Missing start boundary
	at com.helger.as2lib.exception.WrappedOpenAS2Exception.wrap(WrappedOpenAS2Exception.java:66) ~[as2-lib-4.4.4.jar!/:4.4.4]
	at com.helger.as2lib.processor.receiver.net.AS2MDNReceiverHandler.receiveMDN(AS2MDNReceiverHandler.java:291) ~[classes!/:4.4.4]
	at com.helger.as2lib.processor.receiver.net.AS2MDNReceiverHandler.handle(AS2MDNReceiverHandler.java:173) [classes!/:4.4.4]
	at com.helger.as2lib.processor.receiver.AbstractActiveNetModule$ConnectionThread.run(AbstractActiveNetModule.java:264) [as2-lib-4.4.4.jar!/:4.4.4]
**Caused by: javax.mail.internet.ParseException: Missing start boundary**
	at javax.mail.internet.MimeMultipart.parse(MimeMultipart.java:680) ~[javax.mail-1.6.2.jar!/:1.6.2]
	at javax.mail.internet.MimeBodyPart.getContent(MimeBodyPart.java:698) ~[javax.mail-1.6.2.jar!/:1.6.2]
	at com.helger.as2lib.crypto.BCCryptoHelper.verify(BCCryptoHelper.java:696) ~[as2-lib-4.4.4.jar!/:4.4.4]
	at com.helger.as2lib.util.AS2Helper.parseMDN(AS2Helper.java:404) ~[as2-lib-4.4.4.jar!/:4.4.4]
	at com.helger.as2lib.processor.receiver.net.AS2MDNReceiverHandler.receiveMDN(AS2MDNReceiverHandler.java:238) ~[classes!/:4.4.4]
	... 2 more

Do you know how to solve this issue?
Thanks,
Itay

**Comment by phax** [comment]
Hi,
do you eventually have an incoming dump of the message?
It seems like the MDN is not a MIME message but might be something else like plain text or so?

**Comment by ihudedi** [comment]
Hi,
In sync mode the mdn is returned fine.I didnt modify code.It was working in the previous version.

**Comment by ihudedi** [comment]
In version 4.4.2 the sync is also not working and getting disposition type is null.

**Comment by phax** [comment]
Okay, do you have the dump of the incoming MDN for evaluation?

**Comment by ihudedi** [comment]
Hi,
Where do I find the incoming mdn? The mdn that stored in the server before resend him?

**Comment by phax** [comment]
That depends on your setup... and the setup of the sending side.
See the system properties for how to dump incoming messages: https://github.com/phax/as2-lib/wiki/Running

**Comment by ihudedi** [comment]
[ASYNC-as2-incoming-1570473703393-0.http.log](https://github.com/phax/as2-lib/files/3698994/ASYNC-as2-incoming-1570473703393-0.http.log)
[ASYNC-as2-incoming-1570473703565-0.http.log](https://github.com/phax/as2-lib/files/3698995/ASYNC-as2-incoming-1570473703565-0.http.log)
[SYNC-as2-incoming-1570473512359-0.http.log](https://github.com/phax/as2-lib/files/3698996/SYNC-as2-incoming-1570473512359-0.http.log)
[SYNC-as2-incoming-1570473512422-0.http.log](https://github.com/phax/as2-lib/files/3698997/SYNC-as2-incoming-1570473512422-0.http.log)

Attached 4 files from incoming dump.
2 files are sync method that wroks fine ( I modify the file to be SYNC)
2 files are asynced that not working( ASYNC file)
Thanks,
Itay
Please let me know how to resolve the issue.
Thanks a lot,
Itay

**Comment by phax** [comment]
It contains the error message "Large File Support: body was not read yet". That means that dumping is not possible :(

**Comment by phax** [comment]
The last file contains data. And there you can see, that they are sending the header with a newline:
```
Content-Type: multipart/report; report-type=disposition-notification; 
  boundary="----=_Part_30_418994727.1570473512375"
```
May that be the cause for that?

**Comment by ihudedi** [comment]
Last file is sync mode.its working fine.I am testing the async mode via as2 server - sending from client to server and server send back to the same host for return the mdn.only as2 server of you not external as2 server.

**Comment by ihudedi** [comment]
Dont know how to proceed.it was working fine 2-3 months ago.

**Comment by phax** [comment]
Thank you for the explanation. Will check

**Comment by ihudedi** [comment]
If you have any fix for this issue.Please let me know.
Thanks,
Itay

**Comment by phax** [comment]
Sure of course. I'm tracking it down...

**Comment by ihudedi** [comment]
Any updates?

**Comment by phax** [comment]
Can you please try with 4.4.6 - I tried to aligned header handling between receiving and async MDN. thx

**Comment by ihudedi** [comment]
Hi philip,
same issue for 4.4.6
com.helger.as2lib.exception.WrappedOpenAS2Exception: javax.mail.internet.ParseException: Missing start boundary
	at com.helger.as2lib.exception.WrappedOpenAS2Exception.wrap(WrappedOpenAS2Exception.java:66) ~[as2-lib-4.4.6.jar!/:4.4.6]
	at com.helger.as2lib.processor.receiver.net.AS2MDNReceiverHandler.receiveMDN(AS2MDNReceiverHandler.java:303) ~[classes!/:4.4.6]
	at com.helger.as2lib.processor.receiver.net.AS2MDNReceiverHandler.handle(AS2MDNReceiverHandler.java:185) [classes!/:4.4.6]
	at com.helger.as2lib.processor.receiver.AbstractActiveNetModule$ConnectionThread.run(AbstractActiveNetModule.java:264) [as2-lib-4.4.6.jar!/:4.4.6]
Caused by: javax.mail.internet.ParseException: Missing start boundary
	at javax.mail.internet.MimeMultipart.parse(MimeMultipart.java:656) ~[jakarta.mail-1.6.4.jar!/:1.6.4]
	at javax.mail.internet.MimeBodyPart.getContent(MimeBodyPart.java:674) ~[jakarta.mail-1.6.4.jar!/:1.6.4]
	at com.helger.as2lib.crypto.BCCryptoHelper.verify(BCCryptoHelper.java:698) ~[as2-lib-4.4.6.jar!/:4.4.6]
	at com.helger.as2lib.util.AS2Helper.parseMDN(AS2Helper.java:404) ~[as2-lib-4.4.6.jar!/:4.4.6]
	at com.helger.as2lib.processor.receiver.net.AS2MDNReceiverHandler.receiveMDN(AS2MDNReceiverHandler.java:250) ~[classes!/:4.4.6]
	... 2 more

**Comment by ihudedi** [comment]
Hi Philip,
I attach the server log regarding async operation.
Maybe you will find something.

**Comment by phax** [comment]
The log is interesting. The boundary at the end is missing. I'm checking if a flush is missing

**Comment by phax** [comment]
I added an explicit `flush` on async MDN. Can you pls test with the 4.4.7-SNAPSHOT version?

**Comment by ihudedi** [comment]
Hi Philip,
Another thing I saw that you are using
javax.mail.internet.MimeMultipart.parse(MimeMultipart.java:656) ~[jakarta.mail-1.6.4.jar!/:1.6.4]
and not using the javax.mail-1.6.1.jar or later as you used in older  versions

**Comment by phax** [comment]
Yes, that is correct, because the Jakarta-artefacts are replacing the old Sun Java EE artefacts (as part of the migration to Eclipse). So this is functionally the same, just a new name

**Comment by ihudedi** [comment]
Hi Philip,
I can't download the snapshot version in my office.could you register it as version not snapshot?

**Comment by phax** [comment]
Can you manually download from https://oss.sonatype.org/content/repositories/snapshots/com/helger/as2-lib/4.4.7-SNAPSHOT/ - I don't want to make a release that does not work ;-)
And than use it locally as 4.4.7 with this: https://stackoverflow.com/questions/44697389/run-maven-build-with-manually-downloaded-dependencies
hth

**Comment by ihudedi** [comment]
The fix is in as2-lib.jar ?

**Comment by phax** [comment]
Hopefully. I want you to test before I release :D

**Comment by ihudedi** [comment]
So I need to replace as2-lib.jar and as2-server.jar and that is?

**Comment by phax** [comment]
Yes exactly. Just grab them from oss.sonatype.org and replace them. Than test pls :)

**Comment by ihudedi** [comment]
Same issue.
Attahch log.
I replace in my env the 4.4.6 version with latest 4.4.7-snapshot
[async.log](https://github.com/phax/as2-lib/files/3754657/async.log)

**Comment by phax** [comment]
Okay, I tried to fix it. The sending of the async MDN happened asynchronously what makes no sense and causes a lot of issues (as you can see in your logfile). So I made the sending synchronously, especially because the "async" in "async MDN" only refers to the receipt of the original message, but not to the sending process itself.
Additionally I added a missing unification (avoid multiline values) that should do the trick.
So please download again the JAR files (filename is "...-6...") and try one more time. If it works now, I will build a release asap.

**Comment by ihudedi** [comment]
HI Philip,
It solved the issue.
Please also in AS2SenderModule::storePendingInfo

final String sPendingFolder = FilenameHelper.**getAsSecureValidASCIIFilename** (getSession ().getMessageProcessor ()
                                                                                               .attrs ()
                                                                                               .getAsString (ATTR_PENDINGMDNINFO));
      final String sMsgFilename = AS2IOHelper.getFilenameFromMessageID (aMsg.getMessageID ());
      final String sPendingFilename = FilenameHelper.**getAsSecureValidASCIIFilename** (getSession ().getMessageProcessor ()
                                                                                                 .attrs ()
                                                                                                 .getAsString (ATTR_PENDINGMDN)) +
                                      "/" +
                                      sMsgFilename;


remove the call to getAsSecureValidASCIIFilename  for folders.it's needed for filenames becasue 
sPendingFolder can be start with \\
also for sPendingFilename  that contains the folder name.

Thanks a lot ,
Itay

**Comment by ihudedi** [comment]
Please let me know when the 4.4.7 release can be ready for download including the minor fix in AS2SenderModule

**Comment by phax** [comment]
Thanks for testing - will do :)

**Comment by ihudedi** [comment]
I am really need this version.When you finish repack the version just email me.
Thanks a lot for your time and dedication.
Really appreciate.
Itay

**Comment by phax** [comment]
Release 4.4.7 is available, fixing both issues

**Comment by phax** [comment]
4.4.8-SNAPSHOT does the trick

**Comment by ihudedi** [comment]
Hi Philip, could you please create version 4.4.8? I would like to use this version.10x:)

**Comment by ihudedi** [comment]
Thanks for the quick response
Waiting for release 4.4.8

**Comment by ihudedi** [comment]
Is it possible to issue 4.4.8?

**Comment by phax** [comment]
yes later. I am on vacation. .

**Comment by ihudedi** [comment]
10x:) really appreciate your help.

**Comment by phax** [comment]
4.4.8 is out. New requests as new issue pls. Thx.

**Comment by ihudedi** [comment]
10x a lot.
